repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff-check

  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit -c pyproject.toml -r src
        language: python
        pass_filenames: false
        additional_dependencies: ["bandit[toml]==1.8.6"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
